branch-defaults:
  default:
    environment: Project1-env
environment-defaults:
  Project1-env:
    branch: null
    repository: null
global:
  application_name: project-1
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
